### PR TITLE
fix bug + add fedora 20

### PR DESCRIPTION
**Pull request by andykimpe**
fix bug + add fedora 20 support

fedora 21, 22, 23 no working bug named starting

install log fedora 20 http://pastebin.com/ahC85MMX

picture service status

<a href="http://img11.hostingpics.net/pics/673995servicestatus.png"></a>

picture server information

<a href="http://img11.hostingpics.net/pics/232481serverinformation.png"></a>

### CODE REVIEW

**Comment by TGates71** [comment]
@MBlagui @5050

**Comment by andykimpe** [comment]
ok tom I expected a response from pascal or mehdi

ps I like your new logo

**Comment by TGates71** [comment]
Hoping they see it soon ;)

ps: Thanks!

**Comment by andykimpe** [comment]
I have no cares their Skype

have will still leave time to answer them

I would leave them a little message in by Friday

so do not give an answer

**Comment by MBlagui** [comment]
Hmm all changes looks ok he didn't alter any test / routine over the other distrib but no one else have tested this.

**Comment by andykimpe** [comment]
I can leave a test machine if you're available tomorrow mehdi

**Comment by MBlagui** [comment]
On OVH? Best is using DO to validate it but I think they don't care about fedore centos mainly. As it's a small niche.

M B

**Comment by andykimpe** [comment]
sorry for the delay I am very busy now

ovh for it does not offer fedora 20 on their server dedicate only 21 core and 22 server

Fedora 20 and only available on vps and vps of ovh are well known not to work properly with the install of sentora

**Comment by MBlagui** [comment]
Andy was about to merge it but you messed a bit firewall section


     # disable firewall
-    if  [[ "$VER" = "7" ]]; then
-        FIREWALL_SERVICE="firewalld"
-    else 
-        FIREWALL_SERVICE="iptables"
+    if  [["$OS" = "Fedora" ]]; then
+    # install iptables services required to stop iptables
+    $PACKAGE_INSTALLER -y iptables-services
+    systemctl save iptables.service    
+    systemctl stop iptables.service
+    systemctl disable iptables.service
+    # ip6tables for ipv6
+    systemctl save ip6tables.service
+    systemctl stop ip6tables.service
+    systemctl disable ip6tables.service     
+    elif  [[ "$VER" = "7" ]]; then
+    systemctl save firewalld.service
+    systemctl stop firewalld.service
+    systemctl disable firewalld.service
+    else
+    service iptables save
+    service iptables stop
+    chkconfig iptables off
     fi
-    service "$FIREWALL_SERVICE" save
-    service "$FIREWALL_SERVICE" stop
-    chkconfig "$FIREWALL_SERVICE" off

We had a variable for that why getting back the all commands?

@andykimpe

**Pull request closed without merging**
