### PR TITLE
Update httpd

### PR DESCRIPTION
**Pull request by melchormx**
Add default entry for security.

### CODE REVIEW

**Comment by TGates71** [comment]
What is the actual purpose of this? I am not understanding what you are trying to do.

**Comment by Caffe1neAdd1ct** [comment]
Wouldn't this conflict with the panel being the default virtual host? I've not currently got a setup to test on but worth a check.

**Comment by TGates71** [comment]
That is what I am thinking.. I do not understand the reason behind this.

**Comment by Caffe1neAdd1ct** [comment]
@melchormx can you let us know a why and the intended affects?

**Comment by melchormx** [comment]
Therein lies the problem. From my perspective, the panel should be dispatched only through the domain that is defined for it (e.g. panel.mydomain.com) and not by default. Currently, the panel is displayed by default when you enter any domain that points to the server or via ip.

**Comment by TGates71** [comment]
Thanks for the input. Will need more testing to verify that it does not affect the functionality of the panel in any way.
Do your nameservers work properly with this setting? (Do user domains pointed at your server's NS work as intended?)

Also, maybe update it to use the default 404 error page located in /etc/sentora/panel/etc/static/errorpages/404.html for better compatibility.
Testing out this entry now.

**Comment by TGates71** [comment]
Copied from the /panel/ .htaccess file:
```
# Optionally you can uncomment the below line and configure your domain to only allow access from the FQDN.
#RewriteCond %{SERVER_NAME} !^sentora\.domain\.com$ 
#RewriteRule ^ - [F]
```

**Comment by 5050** [comment]
Already done

**Pull request closed without merging**
