### PR TITLE
Update Sohosin Install Version from 0.9.37 to 0.9.37.1

### PR DESCRIPTION
**Pull request by techjwalker**
Update Suhosin install version to latest tested hotfix, which resolves a few previously noted Wordpress issues, include menu items not appearing in editor.

### CODE REVIEW

**Comment by techjwalker** [comment]
Updated previous pull request to properly enumerate the new filename.

**Comment by techjwalker** [comment]
As MB mentioned in the pull https://github.com/sentora/sentora-installers/issues/45, I also agree that using a variable for the version would be nice, though in that case it might be beneficial to reconfigure more of the script to use variable version numbers with an added top-section for defining values.

**Comment by MBlagui** [comment]
check my code 

https://github.com/MBlagui/Sentora-tools/blob/master/suhosin_0.9.37.1.sh

already variable easy we will soft this out.

**Comment by jacobg830** [comment]
:+1: looks good to merge.

me.b's implementation will certainly make it easier while we support the older release of OSs as suhosin will no doubt ditch support for 'old' versions of PHP at some point, though for now your method seems fine.

Would also be good if we could release a easy hotfix on the forums for people having problems :wink:

**Comment by 5050** [comment]
merged, and also updated to put version in variable.

**Pull request merged**
