### PR TITLE
Added support for Debian 7.x (8 soon)

### PR DESCRIPTION
**Pull request by xZero707**
Support for Debian 7.x (Generally tested on 7.8 Wheezy). Support for Debian 8 Jessie (barely tested, but should work).

### CODE REVIEW

**Comment by xZero707** [comment]
Will this one get reviewed or cancelled? Sentora works great on Debian too (Ubuntu is based on Debian), so I don't see the reason to not provide users ability to install it on their Debian boxes.

**Comment by 5050** [comment]
Hi, 

I do not see reason to whole cancel it, but I would apply it more likely if it did not changed the configuration of extensions for ubuntu/debian only (and not centos) around lines 769-770 (original) and if it did not removed the update applied by Me.B at lines 754 to 760 (original)

Are'nt them some change done locally for your needs only ? Can you explain ?

**Comment by jacobg830** [comment]
Think I noticed some small mistakes also.

Line 2 of uninstall/ubuntu-debian.sh no longer has mysql-server which is used by Ubuntu.

Line 769 of sentora_install.sh has a2enmod rewrite removed which, last time I checked, was required by Ubuntu.

I think it would definitely be a good idea to add Debian support though, as it is extremely similar to Ubuntu and one of the most requested operating systems.

**Comment by xZero707** [comment]
I'll fix that issues, and also I noticed issue with package repository insertion for Debian 8 Jessie - It already have PHP 5.6, so there is no need for dotdeb repository.

**Comment by xZero707** [comment]
Checked, and confused. I don't even know how that's happened, that those things got removed. 
As installer needed more than very basic modifications, it involved multiple runs and fails on Debian OS, so perhaps I mistakenly removed those as part of troubleshooting process.
Now is fixed, I'll pull changes. 
Does anybody think that Debian 6 should be included in support? It's obsolete.

**Comment by MBlagui** [comment]
@xZero707 I would be happy if you have a stable modification list to check it with  @5050 .

Could you please check again with the 1.0.3 installer http//sentora.org/install and list all the requested modifications?

I think we may close this pull and add another.

**Comment by xZero707** [comment]
Hi, it's good to hear a voice here, finally! 

I will work on both improved version for 7 and for Debian 8 as well.
We can discuss on the forum.

**Pull request closed without merging**
